### ISSUE TITLE
sdl.set_action decorator breaks autdocs

### ISSUE THREAD

**Issue by BrianJKoopman** [simonsobs/sodetlib#235]
For example, the API for `sodetlib.operations.uxm_setup` is included on the [Setup page](https://simons1.princeton.edu/docs/sodetlib/operations/setup.html?highlight=uxm_setup#module-sodetlib.operations.uxm_setup), however functions that are decorated with `@sdl.set_action()` do not show up when autodoc is used.

**Comment by jlashner** [comment]
Started looking  into this, and the [set_action function in pysmurf](https://github.com/slaclab/pysmurf/blob/a49f96ed2d6c0b24489df2bb82330e40e46ac8c4/python/pysmurf/client/util/pub.py#L32) implements `wraps` and if pysmurf isn't found `set_action` simply returns the original function, which I think should [preserve the docstring](https://github.com/simonsobs/sodetlib/blob/798c403353aa10af7f59978c2f2adc085c2ec479/sodetlib/__init__.py#L12-L15).

I think this is the same as this sphinx issue: https://github.com/sphinx-doc/sphinx/issues/3783, so I'll go through and try to add signatures manually and see if that fixes it

**Comment by jlashner** [comment]
ah nvm figured it out, docs were mocking pysmurf which replaced the set_action function with just a mock. Fixing now
