### ISSUE TITLE
Add sw/fw hashes/ids to get_metadata

### ISSUE THREAD

**Issue by msilvafe** [simonsobs/sodetlib#238]
Add more info to the standard meta data output functions [`get_metadata`](https://github.com/simonsobs/sodetlib/blob/233b8b4eb1aaa56de5dd32f9ab42e80db28e035d/sodetlib/util.py#L152). In particular the following info could be added:
```
import pysmurf
print(f'pysmurf Client version: {pysmurf.__version__}')
epics_prefix="smurf_server_s4"
print(f"Rogue Version: {S._caget(f'{epics_prefix}:AMCc:RogueVersion', as_string=True)}")
print(f"SMuRF Core Version: {S._caget(f'{epics_prefix}:AMCc:SmurfApplication:SmurfVersion', as_string=True)}")
print(f"FPGA git hash: {S.get_fpga_git_hash_short()}")
print(f"Cryocard fw version: {S.C.get_fw_version()}")
```
I've been adding this to my notebooks and the standard output looks like this:
```
pysmurf Client version: 6.0.0
Rogue Version: v4.11.10
SMuRF Core Version: 6.0.0
FPGA git hash: 02ed52a
Cryocard fw version: (10, 188, 222)
```

**Comment by jlashner** [comment]
_just_ getting around to this, but nice suggestion. I'll make a PR and test it next opportunity. If you can test beforehand just lmk and we can merge!
