### ISSUE TITLE
tunefile data - repeated frequencies, most are assigned to channels that are not -1

### ISSUE THREAD

**Issue by chw3k5** [simonsobs/sodetlib#247]
Tunefiles are expected to have unique frequencies, some tune files repeat exact float frequency values. 

## The data example
For Simons1 path for this Mv11 tune file:
tune_path = /mnt/so1/data/ucsd-k2so/smurf/16463/ufm_mv11/1646318795_uxm_relock/outputs/1646320098_tune.npy

## The issue
The frequency 3944.6820000000002 was repeated 10 times,
  9 times this frequency was assigned to a smurf channel: [(0, 87), (0, 89), (0, 187), (0, 199), (0, 223), (0, 232), (0, 236), (0, 256), (0, 276)]
The frequency 4444.048 was repeated 6 times,
  5 times this frequency was assigned to a smurf channel: [(1, 99), (1, 172), (1, 195), (1, 324), (1, 486)]
The frequency 4944.726 was repeated 3 times,
  2 times this frequency was assigned to a smurf channel: [(2, 101), (2, 409)]
The frequency 5444.0 was repeated 7 times,
  6 times this frequency was assigned to a smurf channel: [(3, 45), (3, 162), (3, 287), (3, 299), (3, 394), (3, 476)]
The frequency 5944.296 was repeated 9 times,
  7 times this frequency was assigned to a smurf channel: [(4, 35), (4, 163), (4, 170), (4, 189), (4, 216), (4, 364), (4, 482)]
The frequency 6444.512 was repeated 2 times,
  2 times this frequency was assigned to a smurf channel: [(5, 31), (5, 40)]
The frequency 6944.298 was repeated 5 times,
  5 times this frequency was assigned to a smurf channel: [(6, 299), (6, 323), (6, 341), (6, 447), (6, 490)]
The frequency 7444.818 was repeated 12 times,
  11 times this frequency was assigned to a smurf channel: [(7, 36), (7, 63), (7, 88), (7, 95), (7, 210), (7, 267), (7, 272), (7, 352), (7, 381), (7, 443), (7, 461)]

## Other Notes

DetMap tolerates this issue and only allows one of the repeated frequencies, to make the results consistent the resonator data with the largest SMuRF channel number is kept. Still, I have it make a noisy user warning.

## The test code
```
import os
from warnings import warn
import numpy as np

"""
# Simons1 path for this Mv11 tune file:
tune_path = /mnt/so1/data/ucsd-k2so/smurf/16463/ufm_mv11/1646318795_uxm_relock/outputs/1646320098_tune.npy
"""
# read the tune file
detmap_path, scratch_dir = os.path.split(os.getcwd())
tune_path = os.path.join(detmap_path, 'input', 'tunes', '1646320098_tune.npy')
tunefile_data = np.load(tune_path, allow_pickle=True).item()

# loop over the bands in order
unique_frequencies = {}
repeated_frequencies = {}
for smurf_band in sorted(list(tunefile_data.keys())):
    data_this_band = tunefile_data[smurf_band]
    # resonances may not be present in all bands
    if 'resonances' in data_this_band.keys():
        # loop over the tune data in this band
        resonator_data_this_band = data_this_band['resonances']
        available_res_indexes = sorted(resonator_data_this_band.keys())
        for res_key in available_res_indexes:
            single_res = resonator_data_this_band[res_key]
            single_res['band'] = smurf_band
            reported_freq = single_res['freq']
            # do uniqueness check
            if reported_freq in repeated_frequencies.keys():
                repeated_frequencies[reported_freq].append(single_res)
            elif reported_freq in unique_frequencies.keys():
                single_res_prior = unique_frequencies[reported_freq]
                repeated_frequencies[reported_freq] = [single_res_prior, single_res]
                del unique_frequencies[reported_freq]
            else:
                unique_frequencies[reported_freq] = single_res
# print an out report with the collected data.
if repeated_frequencies:
    warn(f'\nTunefile: {tune_path}\n' +
         f'has duplicated frequency for {len(repeated_frequencies)} frequencies.')
    repeated_frequencies_on_channels = {}
    expected_q = {}
    for repeated_freq in sorted(repeated_frequencies.keys()):
        channel_list = []
        expected_q_this_freq = []
        for single_res in repeated_frequencies[repeated_freq]:
            if single_res['channel'] != -1:
                channel_list.append(single_res)
            if single_res['Q'] != 1:
                expected_q_this_freq.append(single_res)

        channels_str = '.'
        if channel_list:
            repeated_frequencies_on_channels[repeated_freq] = channel_list
            band_channel_list = sorted([(single_res['band'], single_res['channel']) for single_res in channel_list])
            channels_str = f',\n  {len(band_channel_list)} times this frequency was assigned to a ' + \
                           f'smurf channel: {band_channel_list}'
        if expected_q_this_freq:
            expected_q[repeated_freq] = expected_q_this_freq
        print(f'The frequency {repeated_freq} was repeated {len(repeated_frequencies[repeated_freq])} times' +
              f'{channels_str}')
else:
    print(f'{len(unique_frequencies)} found in the tunefile: {tune_path}')

```

**Comment by kmharrington** [comment]
This is an error we should submit to pysmurf: https://github.com/slaclab/pysmurf
