### ISSUE TITLE
iv_analysis returns NaN for whole bias group R_n, p_sat.

### ISSUE THREAD

**Issue by dpdutcher** [simonsobs/sodetlib#274]
P_sat calculation is skipped for channels with NaN R_n, and R_n is calculated using np.mean.
Similar to #268 , I've seen NaNs in iva.resp occur across a whole bias line, and the R_n calculation will then make several other quantities NaN.

Going to replace all calls to np.mean to np.nanmean.

**Comment by jlashner** [comment]
Closed w/ #275
