### ISSUE TITLE
Change default behavior for setup_amps.

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sodetlib#291]
Can we make `setup_amps` not throw and error if `cfg.dev.exp["amps_to_bias "]` is an empty list? Instead could we make it just return quietly? Or maybe return with a log statement? If the list is empty it should really just do nothing. 

I just wanted to ignore slot 3 amplifiers for a bit....

**Comment by jlashner** [comment]
Is it ok if we instead add a `skip_setup_amps` kwarg? I'm worried about manually setting amps_to_bias to the empty list because then it'll be written to disk and we have to remember to set it back after.

**Comment by kmharrington** [comment]
yeah that's fine. I also noticed / learned that got written to disk...

**Comment by jlashner** [comment]
Added `skip_setup_amps`  in #315
