### ISSUE TITLE
Add median bias levels into the noise data saved by take noise?

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sodetlib#294]
I've realized my instant first question about any of the noise data I'm loading is "were the detectors biased." It would probably be nice to just have the information in the same files.

**Comment by jlashner** [comment]
ah yeah the bipolar bias voltages should definitely be added to the metadata object. Is that what you mean by median bias levels?

**Comment by kmharrington** [comment]
yeah, I just want one value per bias line though. Not one per line per time sample.

**Comment by jlashner** [comment]
Just wanted to note that in addition to this we'll also need the current-mode array to fully interpret
