### ISSUE TITLE
mismatching attribute name in plot_Rfrac

### ISSUE THREAD

**Issue by yuhanwyhan** [simonsobs/sodetlib#325]
https://github.com/simonsobs/sodetlib/blob/4bd67b4726c8a3b5be83c2b8a7c4b01f83a68a4d/sodetlib/operations/bias_steps.py#L963

is addressing Rfracs = bsa.R0 / iva.R_n_IV[chmap]
but in iva, the variable name seems should be R_n

https://github.com/simonsobs/sodetlib/blob/4bd67b4726c8a3b5be83c2b8a7c4b01f83a68a4d/sodetlib/operations/iv.py#L75

**Comment by dpdutcher** [comment]
Whoops

**Comment by dpdutcher** [comment]
Fixed 556c675
