### ISSUE TITLE
Disable compression during bias steps

### ISSUE THREAD

**Issue by jlashner** [simonsobs/sodetlib#375]
At site we're having an issue where the streamers are taking too long to compress data when running bias steps on all channels, and this causes runaway frame lengths that end up crashing the streamer.

I don't understand why this is a problem now while it didn't used to be an issue, and it's not an issue when I test on my local computer...

I think, at least for the time being, we'll need to disable compression during bias steps. We should add `enable_compression` this as an option to `stream_g3_on` that defaults to True, so we can disable only when running bias steps, but enable at all other times.

**Comment by dpdutcher** [comment]
solved by #377
