### ISSUE TITLE
Bias step rebiasing tagged incorrectly

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sodetlib#397]
Looking at observations starting to come out of satp3, looks like rebiasing with bias steps isn't tagging things the way we'd like. They're all tagged as `oper,bias_steps,oper,biasstep_rebias`. We'll want to fix this because it's going to create a whole lot of unnecessary books

**Comment by ykyohei** [comment]
Let us confirm to make sure. Is it correct that the tagging needs to be corrected from ` oper,bias_steps,oper,biasstep_rebias` to `oper,bias_steps` ?

**Comment by jlashner** [comment]
The PR above fixes the issue, the tag should be `oper,biasstep_rebias,<user-specified tags>`
