### ISSUE TITLE
Add sodetlib version to get_metadata

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sodetlib#436]
When were changing analysis methods in different on-site operations, we need to know which versions of analysis are in which data files. At a minimum I think we need the sodetlib version in https://github.com/simonsobs/sodetlib/blob/master/sodetlib/util.py#L187 

We should probably also make analysis changes be a tagged release?

**Comment by jlashner** [comment]
I definitely support more frequent tagged releases, especially for analysis changes.
